### PR TITLE
Updates project to Swift 4.2.

### PR DESCRIPTION
**Pull request by hyerra**
Didn't require any major changes but configures the project to use Swift 4.2.

### CODE REVIEW

**Comment by frederoni** [comment]
Looks good.
Please resync your fork and rebase atop master to get CI ✅ .

**Comment by hyerra** [comment]
Hmm, it doesn't look like master has the CI stuff in it yet, though. Should I rebase atop your branch or wait till it gets synced into master?

**Comment by frederoni** [comment]
🤦‍♂️  sorry about that. I'll try to get #84 merged ASAP.

**Comment by hyerra** [comment]
No worries :)!

**Comment by hyerra** [comment]
All checks successful!

**Pull request merged**
